global:
  scrape_interval: 15s

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8000']
    authorization:
      type: Bearer
      credentials: 'your_secret_token_here'